# Generated by Django 5.1.3 on 2024-11-18 09:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('upi_id', models.CharField(max_length=100, unique=True)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be 12 digits long.', regex='^\\d{12}$')])),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='Teenager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('upi_id', models.CharField(max_length=100)),
                ('aadhaar_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be 12 digits long.', regex='^\\d{12}$')])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teenagers', to='teenfinapp.parent')),
            ],
            options={
                'verbose_name': 'Teenager',
                'verbose_name_plural': 'Teenagers',
            },
        ),
        migrations.CreateModel(
            name='MonthlySaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal_description', models.TextField(blank=True, null=True)),
                ('teenager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_savings', to='teenfinapp.teenager')),
            ],
            options={
                'verbose_name': 'Monthly Saving',
                'verbose_name_plural': 'Monthly Savings',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Rent', 'Rent/Dormitory Fees'), ('Food', 'Food'), ('Tuition', 'Tuition and Fees'), ('Transportation', 'Transportation'), ('Shopping', 'Shopping'), ('Entertainment', 'Movie/Events'), ('PhoneBill', 'Phone Bill'), ('Loans', 'Student Loans')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('teenager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_expenses', to='teenfinapp.teenager')),
            ],
            options={
                'verbose_name': 'Daily Expense',
                'verbose_name_plural': 'Daily Expenses',
                'ordering': ['date'],
            },
        ),
    ]
