# Generated by Django 5.1.3 on 2024-11-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenfinapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Rent', 'Rent/Dormitory Fees'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Tuition', 'Tuition and Fees'), ('Supplies', 'Textbooks and Supplies'), ('Transportation', 'Transportation'), ('Clothing', 'Clothing and Accessories'), ('PersonalCare', 'Personal Care'), ('Entertainment', 'Entertainment'), ('PhoneBill', 'Phone Bill'), ('HealthInsurance', 'Health Insurance'), ('Loans', 'Student Loans'), ('EmergencyFund', 'Emergency Fund')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('teenager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_expenses', to='teenfinapp.teenager')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal_description', models.TextField(blank=True, null=True)),
                ('teenager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_savings', to='teenfinapp.teenager')),
            ],
        ),
    ]
