# Generated by Django 5.1.3 on 2024-12-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_remove_income_user_remove_savings_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
